### PR TITLE
chore: bumps booster parent and arquillian dependencies version.

### PR DESCRIPTION
**Pull request by hemanik**
- Bumps Booster Parent version from 20 to 21.
- Bumps Arquillian version from 1.3.0.Final to 1.4.0.Final

### CODE REVIEW

**Comment by metacosm** [comment]
Hi @hemanik, what are the intended benefits of that upgrade? Has this been tested?
Note that runtime owners are not mandated to update the booster parent. What does 21 change?

**Comment by hemanik** [comment]
Hi @metacosm, we have a bunch of improvements around Cube which we would like to contribute to boosters. This update has been done with the booster-parent release version 21.
This PR is to propagate the changes to spring-boot-boosters.

**Comment by metacosm** [comment]
Hi @hemanik, it makes sense indeed. However, have these changes been tested via integration tests?

**Comment by hemanik** [comment]
Hi @metacosm, I have locally tested the boosters with the change and we have integration tests for the Cube in place. Are you looking for some specific integration tests?

**Review by metacosm — APPROVED** [review]

**Comment by hemanik** [comment]
Thank you @metacosm, can you also release a new version with this fix so I can update the boosters with Cube improvements?

**Comment by metacosm** [comment]
That's the plan but I'm not sure when I get around to it, probably not before next Tuesday.

**Pull request merged**
